version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: natours-app
    container_name: natours-app-container
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-network


networks:
  api-network:
    driver: bridge
